spring:
  application:
    name: api-gateway-service

server:
  port: 8302
zuul:
  prefix: /api
  routes:
    user-manager-service: /user-manager/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
